// src/icons.js
import {
  faCoffee,
  faAt,
  faCheck,
  faHome,
  faCircleUser,
  faBook,
  faRocket,
  faCircleInfo,
  faLink,
  faArrowLeft,
  faArrowRight,
  faCircleArrowLeft,
  faCircleArrowRight,
  faPlay,
  faSmile,
  faCode,
  faDotCircle,
  faPlus,
  faContactCard,
  faCircleCheck,
  faCircle,
  faCircleNodes,
  faChair,
  faArrowAltCircleRight,
} from "@fortawesome/free-solid-svg-icons";
import {
  faGit,
  faGithub,
  faGooglePlusG,
  faLinkedin,
  faTelegram,
} from "@fortawesome/free-brands-svg-icons";
import { faLine } from "@fortawesome/free-brands-svg-icons/faLine";

export const icons = {
  coffee: faCoffee,
  at: faContactCard,
  check: faCheck,
  home: faHome,
  user: faCircleUser,
  book: faBook,
  rocket: faRocket,
  info: faCircleInfo,
  linkedIn: faLinkedin,
  github: faGithub,
  leftArrow: faCircleArrowLeft,
  rightArrow: faCircleArrowRight,
  play: faPlay,
  code: faCode,
  dot: faDotCircle,
  plus: faPlus,
};
